/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package inventory;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Blob;

public class Invntory extends javax.swing.JInternalFrame {
    
    File f = null;
    String path = null;
    private final ImageIcon format = null;
    String fname = null;
    int s = 0;
    byte[] pimage = null;
    String prod_id;
    private Object date;
    
    
    public Invntory() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inventory = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventory_tab = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        id_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        price_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        stock_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        date_format = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        add_button = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        clear_button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        des_txt = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();

        Inventory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel2.setText("Inventory");
        Inventory.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 100, 30));

        inventory_tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Stock", "Price", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(inventory_tab);

        Inventory.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 680, 480));
        Inventory.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 181, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel4.setText("Description:");
        Inventory.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, -1, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel6.setText("Product ID:");
        Inventory.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 70, 20));
        Inventory.add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 250, -1));
        Inventory.add(id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 270, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel7.setText("Product Name:");
        Inventory.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 90, 20));
        Inventory.add(price_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 300, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel8.setText("Stock:");
        Inventory.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 40, 20));
        Inventory.add(stock_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 300, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel9.setText("Price:");
        Inventory.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, -1, 20));
        Inventory.add(date_format, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 300, -1));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Inventory.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, 250, 150));

        jButton2.setText("Import");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Inventory.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 530, -1, -1));

        add_button.setText("Add");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });
        Inventory.add(add_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 80, -1));

        jButton6.setText("Update");
        Inventory.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, 80, -1));

        delete_button.setText("Delete");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });
        Inventory.add(delete_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 330, 80, -1));

        clear_button.setText("Clear");
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });
        Inventory.add(clear_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 330, 80, -1));

        jScrollPane2.setViewportView(des_txt);

        Inventory.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 270, 120));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel10.setText("Date:");
        Inventory.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter fnwf = new FileNameExtensionFilter("PNG, JPG,JPEG","png","jpeg","jpg");
        fileChooser.addChoosableFileFilter(fnwf);
        int load = fileChooser.showOpenDialog(null);
        if(load==JFileChooser.APPROVE_OPTION){
            f = fileChooser.getSelectedFile();

            path = f.getAbsolutePath();
            //imagePath.setText(path);
            ImageIcon ii = new ImageIcon(path);
            Image img = ii.getImage().getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
            jLabel3.setIcon(new ImageIcon(img));
        }

    }//GEN-LAST:event_jButton2ActionPerformed

         Connection con1;
         PreparedStatement insert; 
         
         private void table_update(){
             
             int c;
             
        java.util.Date selectedDate = date_format.getDate();
        java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("yyyy-MM-dd");
        System.out.println("Selected Date: " + date_format);
        java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());

        try {
            
            String name = name_txt.getText();
            String stock = stock_txt.getText();
            String price = price_txt.getText();
            String formattedDate = dateFormat.format(selectedDate);
            String description = des_txt.getText();
            

            Class.forName("com.mysql.jdbc.Driver");

            con1 = DriverManager.getConnection("jdbc:mysql://localhost/inventory_store","root","");
            insert = con1.prepareStatement("SELECT* FROM inventory_jtable");

            insert.setString(1, name);
            insert.setString(2, stock);
            insert.setString(3, price);
            insert.setDate(4, sqlDate);
            insert.setString(5, description);

            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Product Added Successfully!");
            
            name_txt.setText("");
            stock_txt.setText("");
            price_txt.setText("");
            date_format.setDate(selectedDate);
            des_txt.setText("");
         
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error occurred while adding product: " + ex.getMessage());
            Logger.getLogger(Invntory.class.getName()).log(Level.SEVERE, null, ex);
        }
    
         }
 
         
    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed

        java.util.Date selectedDate = date_format.getDate();
        java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("yyyy-MM-dd");
        System.out.println("Selected Date: " + date_format);
        java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());
       
        try {
        String name = name_txt.getText();
        String stock = stock_txt.getText();
        String price = price_txt.getText();
        String formattedDate = dateFormat.format(selectedDate);
        String description = des_txt.getText();
            
            

            Class.forName("com.mysql.cj.jdbc.Driver");
        
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/inventory_store","root","");
            insert = con1.prepareStatement("INSERT INTO `inventory_jtable`(Product_name, Stock, Price, Date, Description, Picture) VALUES (?,?,?,?,?, ?)");
            insert.setString(1, name);
            insert.setString(2, stock);
            insert.setString(3, price);
            insert.setDate(4, sqlDate);
            insert.setString(5, description);
            
             
            insert.execute();
            
            
            JOptionPane.showMessageDialog(this,"Product Added Successfully!");
            
            name_txt.setText("");
            stock_txt.setText("");
            price_txt.setText("");
            date_format.setDate(selectedDate);
            des_txt.setText("");
            
            
                   
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error occurred while adding product: " + ex.getMessage());
            Logger.getLogger(Invntory.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                 
    }//GEN-LAST:event_add_buttonActionPerformed

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
         
        id_txt.setText("");
        name_txt.setText("");
        stock_txt.setText("");
        price_txt.setText("");
        des_txt.setText("");
        date_format.setDate(null);
     
        
    }//GEN-LAST:event_clear_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
       
        
    }//GEN-LAST:event_delete_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Inventory;
    private javax.swing.JButton add_button;
    private javax.swing.JButton clear_button;
    private com.toedter.calendar.JDateChooser date_format;
    private javax.swing.JButton delete_button;
    private javax.swing.JTextPane des_txt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JTable inventory_tab;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField price_txt;
    private javax.swing.JTextField stock_txt;
    // End of variables declaration//GEN-END:variables

   

   
}
